name: release
run-name: Build & publish plugin release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup PNPM@9
        uses: pnpm/action-setup@v4
        with:
          version: "9.4.0"

      - name: Build frontend from source
        run: |
          pnpm i
          pnpm run build

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build plugin ZIP
        run: |
          $(pwd)/cli/decky plugin build $(pwd)

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: out/${{ github.event.repository.name }}.zip
          generate_release_notes: true
